window.BI_DATA = {
  "summary": {
    "total_sales": 4204695.0,
    "estimated_margin_upside": 67974.0,
    "critical_opportunities": 11,
    "avg_fill_rate": 93.3,
    "data_trust_fails": 11,
    "published_assets": 3
  },
  "customers": [
    {
      "customer_id": "CUST01",
      "customer_name": "Central Market Group",
      "channel": "Conventional grocery",
      "banners": 7,
      "stores": 1285,
      "region": "Central",
      "planning_owner": "Customer planning"
    },
    {
      "customer_id": "CUST02",
      "customer_name": "Sproutline Natural Markets",
      "channel": "Natural grocery",
      "banners": 1,
      "stores": 424,
      "region": "West",
      "planning_owner": "Natural channel"
    },
    {
      "customer_id": "CUST03",
      "customer_name": "Northstar Independent Co-op",
      "channel": "Independent grocery",
      "banners": 18,
      "stores": 612,
      "region": "North",
      "planning_owner": "Independent accounts"
    },
    {
      "customer_id": "CUST04",
      "customer_name": "Fresh Table Supermarkets",
      "channel": "Regional grocery",
      "banners": 3,
      "stores": 286,
      "region": "Southeast",
      "planning_owner": "Regional accounts"
    },
    {
      "customer_id": "CUST05",
      "customer_name": "Urban Pantry Express",
      "channel": "Small format",
      "banners": 2,
      "stores": 338,
      "region": "Midwest",
      "planning_owner": "Emerging formats"
    }
  ],
  "categories": [
    {
      "category_id": "CAT01",
      "category": "Functional Beverages",
      "department": "Refrigerated",
      "gross_margin_pct": 0.34,
      "target_acv_pct": 88
    },
    {
      "category_id": "CAT02",
      "category": "Better-for-You Snacks",
      "department": "Grocery",
      "gross_margin_pct": 0.31,
      "target_acv_pct": 90
    },
    {
      "category_id": "CAT03",
      "category": "Plant-Based Meals",
      "department": "Frozen",
      "gross_margin_pct": 0.29,
      "target_acv_pct": 84
    },
    {
      "category_id": "CAT04",
      "category": "Natural Personal Care",
      "department": "Wellness",
      "gross_margin_pct": 0.37,
      "target_acv_pct": 80
    },
    {
      "category_id": "CAT05",
      "category": "Organic Pantry Staples",
      "department": "Grocery",
      "gross_margin_pct": 0.25,
      "target_acv_pct": 92
    },
    {
      "category_id": "CAT06",
      "category": "Fresh Specialty Cheese",
      "department": "Fresh",
      "gross_margin_pct": 0.33,
      "target_acv_pct": 76
    }
  ],
  "opportunities": [
    {
      "customer_id": "CUST05",
      "customer_name": "Urban Pantry Express",
      "category_id": "CAT02",
      "category": "Better-for-You Snacks",
      "net_sales": 92457.17,
      "avg_acv_distribution_pct": 85.4,
      "acv_gap_pct": 4.6,
      "syndicated_share_pct": 30.5,
      "competitor_share_pct": 28.3,
      "fill_rate_pct": 82.8,
      "promotion_lift_attainment_pct": 65.3,
      "category_growth_pct": 8.2,
      "panel_repeat_rate_pct": 30.1,
      "estimated_margin_upside": 6837.16,
      "confidence_score": 74.8,
      "opportunity_score": 68.8,
      "recommended_action": "Resolve fill-rate and inventory constraint before customer review"
    },
    {
      "customer_id": "CUST01",
      "customer_name": "Central Market Group",
      "category_id": "CAT06",
      "category": "Fresh Specialty Cheese",
      "net_sales": 180534.85,
      "avg_acv_distribution_pct": 71.6,
      "acv_gap_pct": 4.4,
      "syndicated_share_pct": 30.7,
      "competitor_share_pct": 28.2,
      "fill_rate_pct": 87.7,
      "promotion_lift_attainment_pct": 64.7,
      "category_growth_pct": 9.0,
      "panel_repeat_rate_pct": 30.8,
      "estimated_margin_upside": 11701.71,
      "confidence_score": 82.5,
      "opportunity_score": 61.3,
      "recommended_action": "Resolve fill-rate and inventory constraint before customer review"
    },
    {
      "customer_id": "CUST05",
      "customer_name": "Urban Pantry Express",
      "category_id": "CAT03",
      "category": "Plant-Based Meals",
      "net_sales": 84842.63,
      "avg_acv_distribution_pct": 79.5,
      "acv_gap_pct": 4.5,
      "syndicated_share_pct": 28.8,
      "competitor_share_pct": 27.1,
      "fill_rate_pct": 81.3,
      "promotion_lift_attainment_pct": 74.9,
      "category_growth_pct": 5.6,
      "panel_repeat_rate_pct": 31.2,
      "estimated_margin_upside": 5474.68,
      "confidence_score": 68.0,
      "opportunity_score": 60.7,
      "recommended_action": "Resolve fill-rate and inventory constraint before customer review"
    },
    {
      "customer_id": "CUST05",
      "customer_name": "Urban Pantry Express",
      "category_id": "CAT06",
      "category": "Fresh Specialty Cheese",
      "net_sales": 82850.86,
      "avg_acv_distribution_pct": 71.5,
      "acv_gap_pct": 4.5,
      "syndicated_share_pct": 30.6,
      "competitor_share_pct": 28.0,
      "fill_rate_pct": 79.0,
      "promotion_lift_attainment_pct": 89.1,
      "category_growth_pct": 9.3,
      "panel_repeat_rate_pct": 31.9,
      "estimated_margin_upside": 5600.2,
      "confidence_score": 64.6,
      "opportunity_score": 59.0,
      "recommended_action": "Resolve fill-rate and inventory constraint before customer review"
    },
    {
      "customer_id": "CUST03",
      "customer_name": "Northstar Independent Co-op",
      "category_id": "CAT06",
      "category": "Fresh Specialty Cheese",
      "net_sales": 111700.45,
      "avg_acv_distribution_pct": 72.0,
      "acv_gap_pct": 4.0,
      "syndicated_share_pct": 29.5,
      "competitor_share_pct": 27.3,
      "fill_rate_pct": 82.9,
      "promotion_lift_attainment_pct": 78.9,
      "category_growth_pct": 9.1,
      "panel_repeat_rate_pct": 30.8,
      "estimated_margin_upside": 7153.0,
      "confidence_score": 74.5,
      "opportunity_score": 57.8,
      "recommended_action": "Resolve fill-rate and inventory constraint before customer review"
    },
    {
      "customer_id": "CUST05",
      "customer_name": "Urban Pantry Express",
      "category_id": "CAT05",
      "category": "Organic Pantry Staples",
      "net_sales": 83429.12,
      "avg_acv_distribution_pct": 87.5,
      "acv_gap_pct": 4.5,
      "syndicated_share_pct": 29.8,
      "competitor_share_pct": 27.6,
      "fill_rate_pct": 84.1,
      "promotion_lift_attainment_pct": 70.3,
      "category_growth_pct": 2.2,
      "panel_repeat_rate_pct": 32.2,
      "estimated_margin_upside": 4444.26,
      "confidence_score": 79.4,
      "opportunity_score": 55.7,
      "recommended_action": "Resolve fill-rate and inventory constraint before customer review"
    },
    {
      "customer_id": "CUST04",
      "customer_name": "Fresh Table Supermarkets",
      "category_id": "CAT02",
      "category": "Better-for-You Snacks",
      "net_sales": 144767.42,
      "avg_acv_distribution_pct": 86.0,
      "acv_gap_pct": 4.0,
      "syndicated_share_pct": 29.2,
      "competitor_share_pct": 27.8,
      "fill_rate_pct": 87.7,
      "promotion_lift_attainment_pct": 65.9,
      "category_growth_pct": 7.6,
      "panel_repeat_rate_pct": 30.3,
      "estimated_margin_upside": 8124.3,
      "confidence_score": 81.6,
      "opportunity_score": 55.1,
      "recommended_action": "Resolve fill-rate and inventory constraint before customer review"
    },
    {
      "customer_id": "CUST03",
      "customer_name": "Northstar Independent Co-op",
      "category_id": "CAT05",
      "category": "Organic Pantry Staples",
      "net_sales": 110191.64,
      "avg_acv_distribution_pct": 86.7,
      "acv_gap_pct": 5.3,
      "syndicated_share_pct": 30.3,
      "competitor_share_pct": 28.0,
      "fill_rate_pct": 86.5,
      "promotion_lift_attainment_pct": 65.3,
      "category_growth_pct": 2.3,
      "panel_repeat_rate_pct": 31.4,
      "estimated_margin_upside": 5518.67,
      "confidence_score": 82.3,
      "opportunity_score": 53.9,
      "recommended_action": "Resolve fill-rate and inventory constraint before customer review"
    },
    {
      "customer_id": "CUST02",
      "customer_name": "Sproutline Natural Markets",
      "category_id": "CAT06",
      "category": "Fresh Specialty Cheese",
      "net_sales": 145536.22,
      "avg_acv_distribution_pct": 72.2,
      "acv_gap_pct": 3.8,
      "syndicated_share_pct": 31.4,
      "competitor_share_pct": 29.4,
      "fill_rate_pct": 86.0,
      "promotion_lift_attainment_pct": 77.5,
      "category_growth_pct": 9.2,
      "panel_repeat_rate_pct": 31.4,
      "estimated_margin_upside": 8140.75,
      "confidence_score": 78.8,
      "opportunity_score": 52.9,
      "recommended_action": "Resolve fill-rate and inventory constraint before customer review"
    },
    {
      "customer_id": "CUST05",
      "customer_name": "Urban Pantry Express",
      "category_id": "CAT01",
      "category": "Functional Beverages",
      "net_sales": 98971.53,
      "avg_acv_distribution_pct": 83.5,
      "acv_gap_pct": 4.5,
      "syndicated_share_pct": 30.3,
      "competitor_share_pct": 28.2,
      "fill_rate_pct": 84.9,
      "promotion_lift_attainment_pct": 94.3,
      "category_growth_pct": 13.9,
      "panel_repeat_rate_pct": 31.7,
      "estimated_margin_upside": 4979.67,
      "confidence_score": 76.3,
      "opportunity_score": 51.6,
      "recommended_action": "Resolve fill-rate and inventory constraint before customer review"
    },
    {
      "customer_id": "CUST04",
      "customer_name": "Fresh Table Supermarkets",
      "category_id": "CAT01",
      "category": "Functional Beverages",
      "net_sales": 140509.91,
      "avg_acv_distribution_pct": 83.2,
      "acv_gap_pct": 4.8,
      "syndicated_share_pct": 31.2,
      "competitor_share_pct": 28.5,
      "fill_rate_pct": 88.2,
      "promotion_lift_attainment_pct": 81.7,
      "category_growth_pct": 14.1,
      "panel_repeat_rate_pct": 31.1,
      "estimated_margin_upside": 6604.1,
      "confidence_score": 87.4,
      "opportunity_score": 51.0,
      "recommended_action": "Resolve fill-rate and inventory constraint before customer review"
    },
    {
      "customer_id": "CUST03",
      "customer_name": "Northstar Independent Co-op",
      "category_id": "CAT04",
      "category": "Natural Personal Care",
      "net_sales": 145915.5,
      "avg_acv_distribution_pct": 75.1,
      "acv_gap_pct": 4.9,
      "syndicated_share_pct": 30.1,
      "competitor_share_pct": 27.8,
      "fill_rate_pct": 89.7,
      "promotion_lift_attainment_pct": 67.4,
      "category_growth_pct": 3.8,
      "panel_repeat_rate_pct": 30.3,
      "estimated_margin_upside": 8885.75,
      "confidence_score": 84.2,
      "opportunity_score": 47.8,
      "recommended_action": "Rebuild promotion story with compliance and lift readout"
    },
    {
      "customer_id": "CUST01",
      "customer_name": "Central Market Group",
      "category_id": "CAT01",
      "category": "Functional Beverages",
      "net_sales": 191502.0,
      "avg_acv_distribution_pct": 82.8,
      "acv_gap_pct": 5.2,
      "syndicated_share_pct": 30.3,
      "competitor_share_pct": 27.7,
      "fill_rate_pct": 89.5,
      "promotion_lift_attainment_pct": 83.5,
      "category_growth_pct": 14.1,
      "panel_repeat_rate_pct": 30.8,
      "estimated_margin_upside": 7965.78,
      "confidence_score": 87.1,
      "opportunity_score": 47.7,
      "recommended_action": "Monitor in recurring business review"
    },
    {
      "customer_id": "CUST02",
      "customer_name": "Sproutline Natural Markets",
      "category_id": "CAT02",
      "category": "Better-for-You Snacks",
      "net_sales": 160656.87,
      "avg_acv_distribution_pct": 84.9,
      "acv_gap_pct": 5.1,
      "syndicated_share_pct": 31.2,
      "competitor_share_pct": 29.1,
      "fill_rate_pct": 88.7,
      "promotion_lift_attainment_pct": 77.6,
      "category_growth_pct": 8.1,
      "panel_repeat_rate_pct": 30.4,
      "estimated_margin_upside": 7373.23,
      "confidence_score": 79.9,
      "opportunity_score": 47.5,
      "recommended_action": "Resolve fill-rate and inventory constraint before customer review"
    },
    {
      "customer_id": "CUST03",
      "customer_name": "Northstar Independent Co-op",
      "category_id": "CAT01",
      "category": "Functional Beverages",
      "net_sales": 123564.98,
      "avg_acv_distribution_pct": 83.0,
      "acv_gap_pct": 5.0,
      "syndicated_share_pct": 30.9,
      "competitor_share_pct": 28.3,
      "fill_rate_pct": 87.2,
      "promotion_lift_attainment_pct": 88.9,
      "category_growth_pct": 14.1,
      "panel_repeat_rate_pct": 30.8,
      "estimated_margin_upside": 5275.24,
      "confidence_score": 76.9,
      "opportunity_score": 47.0,
      "recommended_action": "Resolve fill-rate and inventory constraint before customer review"
    },
    {
      "customer_id": "CUST04",
      "customer_name": "Fresh Table Supermarkets",
      "category_id": "CAT06",
      "category": "Fresh Specialty Cheese",
      "net_sales": 135703.06,
      "avg_acv_distribution_pct": 71.4,
      "acv_gap_pct": 4.6,
      "syndicated_share_pct": 28.2,
      "competitor_share_pct": 26.6,
      "fill_rate_pct": 86.7,
      "promotion_lift_attainment_pct": 97.8,
      "category_growth_pct": 9.0,
      "panel_repeat_rate_pct": 30.6,
      "estimated_margin_upside": 5914.97,
      "confidence_score": 81.6,
      "opportunity_score": 43.0,
      "recommended_action": "Resolve fill-rate and inventory constraint before customer review"
    },
    {
      "customer_id": "CUST04",
      "customer_name": "Fresh Table Supermarkets",
      "category_id": "CAT04",
      "category": "Natural Personal Care",
      "net_sales": 167920.74,
      "avg_acv_distribution_pct": 76.9,
      "acv_gap_pct": 3.1,
      "syndicated_share_pct": 29.0,
      "competitor_share_pct": 27.3,
      "fill_rate_pct": 89.8,
      "promotion_lift_attainment_pct": 69.7,
      "category_growth_pct": 3.7,
      "panel_repeat_rate_pct": 30.5,
      "estimated_margin_upside": 9044.0,
      "confidence_score": 89.6,
      "opportunity_score": 42.2,
      "recommended_action": "Rebuild promotion story with compliance and lift readout"
    },
    {
      "customer_id": "CUST01",
      "customer_name": "Central Market Group",
      "category_id": "CAT04",
      "category": "Natural Personal Care",
      "net_sales": 223042.3,
      "avg_acv_distribution_pct": 75.0,
      "acv_gap_pct": 5.0,
      "syndicated_share_pct": 30.7,
      "competitor_share_pct": 28.2,
      "fill_rate_pct": 90.5,
      "promotion_lift_attainment_pct": 75.5,
      "category_growth_pct": 3.8,
      "panel_repeat_rate_pct": 29.8,
      "estimated_margin_upside": 11416.6,
      "confidence_score": 90.0,
      "opportunity_score": 41.5,
      "recommended_action": "Rebuild promotion story with compliance and lift readout"
    }
  ],
  "trustQueue": [
    {
      "check_id": "DQ048",
      "source_system": "Planning request tracker",
      "table_name": "stakeholder_requests",
      "check_type": "Requirement clarity",
      "severity": "Medium",
      "status": "Fail",
      "freshness_hours": 65,
      "failed_records": 912,
      "owner": "Category manager",
      "recommended_fix": "Certify measure after peer review",
      "trust_score": 55.1
    },
    {
      "check_id": "DQ029",
      "source_system": "Promotion calendar",
      "table_name": "promotion_calendar",
      "check_type": "Promotion join coverage",
      "severity": "High",
      "status": "Fail",
      "freshness_hours": 58,
      "failed_records": 375,
      "owner": "BI analyst",
      "recommended_fix": "Clarify stakeholder metric definition",
      "trust_score": 55.4
    },
    {
      "check_id": "DQ081",
      "source_system": "Retailer direct POS",
      "table_name": "weekly_pos",
      "check_type": "Scan reconciliation",
      "severity": "High",
      "status": "Fail",
      "freshness_hours": 42,
      "failed_records": 611,
      "owner": "Data engineering",
      "recommended_fix": "Reconcile retailer scans to distributor shipments",
      "trust_score": 57.4
    },
    {
      "check_id": "DQ031",
      "source_system": "Syndicated POS",
      "table_name": "weekly_pos",
      "check_type": "Freshness",
      "severity": "High",
      "status": "Watch",
      "freshness_hours": 62,
      "failed_records": 910,
      "owner": "Customer planning",
      "recommended_fix": "Reconcile retailer scans to distributor shipments",
      "trust_score": 60.9
    },
    {
      "check_id": "DQ049",
      "source_system": "Syndicated POS",
      "table_name": "weekly_pos",
      "check_type": "Freshness",
      "severity": "High",
      "status": "Fail",
      "freshness_hours": 41,
      "failed_records": 201,
      "owner": "BI analyst",
      "recommended_fix": "Patch promotion calendar join key",
      "trust_score": 61.1
    },
    {
      "check_id": "DQ063",
      "source_system": "Power BI service",
      "table_name": "power_bi_assets",
      "check_type": "Refresh SLA",
      "severity": "High",
      "status": "Fail",
      "freshness_hours": 41,
      "failed_records": 80,
      "owner": "Category manager",
      "recommended_fix": "Patch promotion calendar join key",
      "trust_score": 62.1
    },
    {
      "check_id": "DQ067",
      "source_system": "Distributor shipment ERP",
      "table_name": "distributor_shipments",
      "check_type": "Order to shipment match",
      "severity": "Critical",
      "status": "Watch",
      "freshness_hours": 4,
      "failed_records": 588,
      "owner": "Data engineering",
      "recommended_fix": "Clarify stakeholder metric definition",
      "trust_score": 65.1
    },
    {
      "check_id": "DQ069",
      "source_system": "Retailer direct POS",
      "table_name": "weekly_pos",
      "check_type": "Scan reconciliation",
      "severity": "High",
      "status": "Watch",
      "freshness_hours": 47,
      "failed_records": 678,
      "owner": "Category manager",
      "recommended_fix": "Align item hierarchy mapping before business review",
      "trust_score": 66.6
    },
    {
      "check_id": "DQ021",
      "source_system": "Syndicated POS",
      "table_name": "weekly_pos",
      "check_type": "Freshness",
      "severity": "Medium",
      "status": "Fail",
      "freshness_hours": 43,
      "failed_records": 183,
      "owner": "Customer planning",
      "recommended_fix": "Patch promotion calendar join key",
      "trust_score": 66.7
    },
    {
      "check_id": "DQ040",
      "source_system": "Item master",
      "table_name": "skus",
      "check_type": "Hierarchy completeness",
      "severity": "Medium",
      "status": "Fail",
      "freshness_hours": 32,
      "failed_records": 520,
      "owner": "BI analyst",
      "recommended_fix": "Backfill missing week and republish dataset",
      "trust_score": 66.7
    },
    {
      "check_id": "DQ023",
      "source_system": "Planning request tracker",
      "table_name": "stakeholder_requests",
      "check_type": "Requirement clarity",
      "severity": "Critical",
      "status": "Pass",
      "freshness_hours": 65,
      "failed_records": 0,
      "owner": "Customer planning",
      "recommended_fix": "Align item hierarchy mapping before business review",
      "trust_score": 67.8
    },
    {
      "check_id": "DQ014",
      "source_system": "Item master",
      "table_name": "skus",
      "check_type": "Hierarchy completeness",
      "severity": "Low",
      "status": "Fail",
      "freshness_hours": 51,
      "failed_records": 250,
      "owner": "Data engineering",
      "recommended_fix": "Patch promotion calendar join key",
      "trust_score": 68.2
    },
    {
      "check_id": "DQ050",
      "source_system": "Promotion calendar",
      "table_name": "promotion_calendar",
      "check_type": "Promotion join coverage",
      "severity": "Critical",
      "status": "Watch",
      "freshness_hours": 9,
      "failed_records": 162,
      "owner": "BI analyst",
      "recommended_fix": "Certify measure after peer review",
      "trust_score": 68.7
    },
    {
      "check_id": "DQ061",
      "source_system": "Item master",
      "table_name": "skus",
      "check_type": "Hierarchy completeness",
      "severity": "Medium",
      "status": "Fail",
      "freshness_hours": 8,
      "failed_records": 496,
      "owner": "Customer planning",
      "recommended_fix": "Patch promotion calendar join key",
      "trust_score": 68.9
    },
    {
      "check_id": "DQ082",
      "source_system": "Retailer direct POS",
      "table_name": "weekly_pos",
      "check_type": "Scan reconciliation",
      "severity": "Low",
      "status": "Watch",
      "freshness_hours": 69,
      "failed_records": 865,
      "owner": "Category manager",
      "recommended_fix": "Certify measure after peer review",
      "trust_score": 69.5
    },
    {
      "check_id": "DQ057",
      "source_system": "Promotion calendar",
      "table_name": "promotion_calendar",
      "check_type": "Promotion join coverage",
      "severity": "Medium",
      "status": "Fail",
      "freshness_hours": 19,
      "failed_records": 309,
      "owner": "Data engineering",
      "recommended_fix": "Reconcile retailer scans to distributor shipments",
      "trust_score": 70.4
    }
  ],
  "packages": [
    {
      "customer_id": "CUST01",
      "customer_name": "Central Market Group",
      "business_review_theme": "Assortment growth story with data quality guardrails",
      "net_sales": 1136152.31,
      "top_categories": "Fresh Specialty Cheese; Functional Beverages; Natural Personal Care",
      "estimated_margin_upside": 31084.09,
      "open_stakeholder_requests": 18,
      "slides_ready": "Needs account signoff",
      "next_meeting": "2026-06-16"
    },
    {
      "customer_id": "CUST02",
      "customer_name": "Sproutline Natural Markets",
      "business_review_theme": "Fill-rate stabilization before expansion ask",
      "net_sales": 943558.25,
      "top_categories": "Fresh Specialty Cheese; Better-for-You Snacks; Natural Personal Care",
      "estimated_margin_upside": 24819.75,
      "open_stakeholder_requests": 15,
      "slides_ready": "Yes",
      "next_meeting": "2026-06-16"
    },
    {
      "customer_id": "CUST03",
      "customer_name": "Northstar Independent Co-op",
      "business_review_theme": "Fill-rate stabilization before expansion ask",
      "net_sales": 731697.21,
      "top_categories": "Fresh Specialty Cheese; Organic Pantry Staples; Natural Personal Care",
      "estimated_margin_upside": 21557.42,
      "open_stakeholder_requests": 30,
      "slides_ready": "Yes",
      "next_meeting": "2026-06-18"
    },
    {
      "customer_id": "CUST04",
      "customer_name": "Fresh Table Supermarkets",
      "business_review_theme": "Fill-rate stabilization before expansion ask",
      "net_sales": 840838.92,
      "top_categories": "Better-for-You Snacks; Functional Beverages; Fresh Specialty Cheese",
      "estimated_margin_upside": 20643.37,
      "open_stakeholder_requests": 18,
      "slides_ready": "Needs source validation",
      "next_meeting": "2026-06-04"
    },
    {
      "customer_id": "CUST05",
      "customer_name": "Urban Pantry Express",
      "business_review_theme": "Fill-rate stabilization before expansion ask",
      "net_sales": 552448.74,
      "top_categories": "Better-for-You Snacks; Plant-Based Meals; Fresh Specialty Cheese",
      "estimated_margin_upside": 17912.04,
      "open_stakeholder_requests": 19,
      "slides_ready": "Yes",
      "next_meeting": "2026-06-09"
    }
  ],
  "assets": [
    {
      "asset_id": "PBI01",
      "asset_name": "Customer Business Review",
      "workspace": "Customer analytics",
      "primary_audience": "Account team",
      "refresh_cadence": "Twice weekly",
      "refresh_success_pct": 91.3,
      "data_quality_pct": 92.7,
      "monthly_active_users": 127,
      "certification_status": "Certified",
      "rls_required": "No"
    },
    {
      "asset_id": "PBI02",
      "asset_name": "Gap and Void Dashboard",
      "workspace": "Category management",
      "primary_audience": "Supplier managers",
      "refresh_cadence": "Weekly",
      "refresh_success_pct": 93.9,
      "data_quality_pct": 76.6,
      "monthly_active_users": 111,
      "certification_status": "Needs review",
      "rls_required": "Yes"
    },
    {
      "asset_id": "PBI03",
      "asset_name": "Promotion Performance",
      "workspace": "Category management",
      "primary_audience": "Customer planning",
      "refresh_cadence": "Weekly",
      "refresh_success_pct": 89.1,
      "data_quality_pct": 78.9,
      "monthly_active_users": 42,
      "certification_status": "Certified",
      "rls_required": "No"
    },
    {
      "asset_id": "PBI04",
      "asset_name": "Fill Rate and Inventory",
      "workspace": "Customer analytics",
      "primary_audience": "Supplier managers",
      "refresh_cadence": "Weekly",
      "refresh_success_pct": 99.5,
      "data_quality_pct": 85.0,
      "monthly_active_users": 88,
      "certification_status": "Needs review",
      "rls_required": "No"
    },
    {
      "asset_id": "PBI05",
      "asset_name": "Category Share Tracker",
      "workspace": "Category management",
      "primary_audience": "Supplier managers",
      "refresh_cadence": "Twice weekly",
      "refresh_success_pct": 95.2,
      "data_quality_pct": 88.6,
      "monthly_active_users": 115,
      "certification_status": "Needs review",
      "rls_required": "Yes"
    },
    {
      "asset_id": "PBI06",
      "asset_name": "Ad Hoc Insights Pack",
      "workspace": "Category management",
      "primary_audience": "Leadership",
      "refresh_cadence": "Weekly",
      "refresh_success_pct": 99.6,
      "data_quality_pct": 93.6,
      "monthly_active_users": 57,
      "certification_status": "Promoted",
      "rls_required": "Yes"
    },
    {
      "asset_id": "PBI07",
      "asset_name": "Supplier Scorecard",
      "workspace": "Customer analytics",
      "primary_audience": "Customer planning",
      "refresh_cadence": "Weekly",
      "refresh_success_pct": 90.4,
      "data_quality_pct": 94.8,
      "monthly_active_users": 91,
      "certification_status": "Needs review",
      "rls_required": "No"
    },
    {
      "asset_id": "PBI08",
      "asset_name": "Forecasted Sales Potential",
      "workspace": "Executive reporting",
      "primary_audience": "Customer planning",
      "refresh_cadence": "Daily",
      "refresh_success_pct": 87.3,
      "data_quality_pct": 97.3,
      "monthly_active_users": 52,
      "certification_status": "Needs review",
      "rls_required": "No"
    }
  ],
  "measures": [
    {
      "measure_name": "Net Sales",
      "grain": "Customer x SKU x week",
      "dax_pattern": "SUM(weekly_pos[sales_dollars])",
      "business_definition": "Retail POS dollars after promoted price effects.",
      "certification_status": "Certified",
      "test_coverage_pct": 94
    },
    {
      "measure_name": "ACV Distribution Gap",
      "grain": "Customer x category x week",
      "dax_pattern": "MAX(categories[target_acv_pct]) - AVERAGE(weekly_pos[acv_distribution_pct])",
      "business_definition": "Points of distribution still needed versus category benchmark.",
      "certification_status": "Certified",
      "test_coverage_pct": 91
    },
    {
      "measure_name": "Fill Rate Risk",
      "grain": "Customer x SKU x week",
      "dax_pattern": "1 - DIVIDE(SUM(shipments[shipped_cases]), SUM(shipments[ordered_cases]))",
      "business_definition": "Unfilled ordered cases as a share of ordered cases.",
      "certification_status": "Promoted",
      "test_coverage_pct": 86
    },
    {
      "measure_name": "Promotion Lift Attainment",
      "grain": "Promotion",
      "dax_pattern": "DIVIDE(AVERAGE(promotions[actual_lift_pct]), AVERAGE(promotions[planned_lift_pct]))",
      "business_definition": "Actual promotion lift versus planned lift.",
      "certification_status": "Needs review",
      "test_coverage_pct": 71
    },
    {
      "measure_name": "Source Trust Score",
      "grain": "Dataset x refresh",
      "dax_pattern": "100 - [Freshness Penalty] - [Failed Record Penalty] - [SLA Penalty]",
      "business_definition": "Composite confidence score used before publishing a business review.",
      "certification_status": "Draft",
      "test_coverage_pct": 68
    }
  ]
};
